# SPDX-License-Identifier: GPL-2.0

# required for overlay support

dtb-$(CONFIG_ARCH_MXC) += \
			   kb-mx8mp-base.dtb \
			   kb-mx8mp-lt8912.dtb \
			   kb-mx8mp-atk-10.dtb \
                           kb-mx8mp-hontron-7.dtb \
                           kb-mx8mp-m190etn01-19.dtb
			   
